### ISSUE TITLE
[component] feature / landing_page / create intro

### ISSUE THREAD

**Issue by NomadHash** [codestates/Moi_Client#7]
### ISSUE
- Group:  `client`,
- Type: `feature`
- Detail: create intro

### TODO
1. [ ] create preview gif block
2. [ ] create page title
3. [ ] create scroll down button

### `2h`
